import streamlit as st
from utils import generate_image_with_diffusers

options = st.sidebar.selectbox("Select your choice", ["Home","Diffusion Model"])

if options == "Home":
  st.title("Text to Image Generation App")
  with st.expander("About the App"):
    st.write("This is an application to create images according to the prompt given!")

elif options == "Diffusion Model":
  st.subheader("Image Generation using HuggingFace Diffusers")
  input_prompt = st.text_input("Enter your text prompt")
  if input_prompt:
    if st.button("Generate Image"):
      image_output = generate_image_with_diffusers(input_prompt)
      st.info("Generating Image...")
      st.success("Image Generated Successfully")
      st.image(image_output, caption="Generated by HuggingFace Diffusers")

